services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: c168kmk.pro-frontend
    ports:
      - "20204:80"
    restart: unless-stopped
    networks:
      - c168kmk.pro-network

networks:
  c168kmk.pro-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.124.0.0/24
